/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_hechler_patrick_pfs_fs_impl_NativePatrFileSys */

#ifndef _Included_de_hechler_patrick_pfs_fs_impl_NativePatrFileSys
#define _Included_de_hechler_patrick_pfs_fs_impl_NativePatrFileSys
#ifdef __cplusplus
extern "C" {
#endif
#undef de_hechler_patrick_pfs_fs_impl_NativePatrFileSys_PFS_OPEN_TRUNCATE
#define de_hechler_patrick_pfs_fs_impl_NativePatrFileSys_PFS_OPEN_TRUNCATE 64L
#undef de_hechler_patrick_pfs_fs_impl_NativePatrFileSys_PFS_OPEN_CREATE
#define de_hechler_patrick_pfs_fs_impl_NativePatrFileSys_PFS_OPEN_CREATE 512L
/*
 * Class:     de_hechler_patrick_pfs_fs_impl_NativePatrFileSys
 * Method:    create
 * Signature: (Ljava/lang/String;)Lde/hechler/patrick/pfs/fs/impl/NativePatrFileSys;
 */
JNIEXPORT jobject JNICALL Java_de_hechler_patrick_pfs_fs_impl_NativePatrFileSys_create__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     de_hechler_patrick_pfs_fs_impl_NativePatrFileSys
 * Method:    create
 * Signature: (Ljava/lang/String;JIII)Lde/hechler/patrick/pfs/fs/impl/NativePatrFileSys;
 */
JNIEXPORT jobject JNICALL Java_de_hechler_patrick_pfs_fs_impl_NativePatrFileSys_create__Ljava_lang_String_2JIII
  (JNIEnv *, jclass, jstring, jlong, jint, jint, jint);

/*
 * Class:     de_hechler_patrick_pfs_fs_impl_NativePatrFileSys
 * Method:    createRamFs
 * Signature: (JI)Lde/hechler/patrick/pfs/fs/impl/NativePatrFileSys;
 */
JNIEXPORT jobject JNICALL Java_de_hechler_patrick_pfs_fs_impl_NativePatrFileSys_createRamFs
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     de_hechler_patrick_pfs_fs_impl_NativePatrFileSys
 * Method:    create
 * Signature: (Lde/hechler/patrick/pfs/bm/BlockManager;)Lde/hechler/patrick/pfs/fs/impl/NativePatrFileSys;
 */
JNIEXPORT jobject JNICALL Java_de_hechler_patrick_pfs_fs_impl_NativePatrFileSys_create__Lde_hechler_patrick_pfs_bm_BlockManager_2
  (JNIEnv *, jclass, jobject);

/*
 * Class:     de_hechler_patrick_pfs_fs_impl_NativePatrFileSys
 * Method:    format
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_hechler_patrick_pfs_fs_impl_NativePatrFileSys_format
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_hechler_patrick_pfs_fs_impl_NativePatrFileSys
 * Method:    root
 * Signature: ()Lde/hechler/patrick/pfs/folder/PFSFolder;
 */
JNIEXPORT jobject JNICALL Java_de_hechler_patrick_pfs_fs_impl_NativePatrFileSys_root
  (JNIEnv *, jobject);

/*
 * Class:     de_hechler_patrick_pfs_fs_impl_NativePatrFileSys
 * Method:    blockCount
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hechler_patrick_pfs_fs_impl_NativePatrFileSys_blockCount
  (JNIEnv *, jobject);

/*
 * Class:     de_hechler_patrick_pfs_fs_impl_NativePatrFileSys
 * Method:    blockSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_hechler_patrick_pfs_fs_impl_NativePatrFileSys_blockSize
  (JNIEnv *, jobject);

/*
 * Class:     de_hechler_patrick_pfs_fs_impl_NativePatrFileSys
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_hechler_patrick_pfs_fs_impl_NativePatrFileSys_close
  (JNIEnv *, jobject);

/*
 * Class:     de_hechler_patrick_pfs_fs_impl_NativePatrFileSys
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_hechler_patrick_pfs_fs_impl_NativePatrFileSys_finalize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
