/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_hechler_patrick_pfs_folder_impl_NativePatrFileSysFolder */

#ifndef _Included_de_hechler_patrick_pfs_folder_impl_NativePatrFileSysFolder
#define _Included_de_hechler_patrick_pfs_folder_impl_NativePatrFileSysFolder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_hechler_patrick_pfs_folder_impl_NativePatrFileSysFolder
 * Method:    getFlags
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hechler_patrick_pfs_folder_impl_NativePatrFileSysFolder_getFlags
  (JNIEnv *, jobject);

/*
 * Class:     de_hechler_patrick_pfs_folder_impl_NativePatrFileSysFolder
 * Method:    modifyFlags
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_de_hechler_patrick_pfs_folder_impl_NativePatrFileSysFolder_modifyFlags
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_hechler_patrick_pfs_folder_impl_NativePatrFileSysFolder
 * Method:    name
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_hechler_patrick_pfs_folder_impl_NativePatrFileSysFolder_name__
  (JNIEnv *, jobject);

/*
 * Class:     de_hechler_patrick_pfs_folder_impl_NativePatrFileSysFolder
 * Method:    name
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_hechler_patrick_pfs_folder_impl_NativePatrFileSysFolder_name__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     de_hechler_patrick_pfs_folder_impl_NativePatrFileSysFolder
 * Method:    createTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hechler_patrick_pfs_folder_impl_NativePatrFileSysFolder_createTime__
  (JNIEnv *, jobject);

/*
 * Class:     de_hechler_patrick_pfs_folder_impl_NativePatrFileSysFolder
 * Method:    createTime
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_hechler_patrick_pfs_folder_impl_NativePatrFileSysFolder_createTime__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_hechler_patrick_pfs_folder_impl_NativePatrFileSysFolder
 * Method:    lastModTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hechler_patrick_pfs_folder_impl_NativePatrFileSysFolder_lastModTime__
  (JNIEnv *, jobject);

/*
 * Class:     de_hechler_patrick_pfs_folder_impl_NativePatrFileSysFolder
 * Method:    lastModTime
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_hechler_patrick_pfs_folder_impl_NativePatrFileSysFolder_lastModTime__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_hechler_patrick_pfs_folder_impl_NativePatrFileSysFolder
 * Method:    delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_hechler_patrick_pfs_folder_impl_NativePatrFileSysFolder_delete
  (JNIEnv *, jobject);

/*
 * Class:     de_hechler_patrick_pfs_folder_impl_NativePatrFileSysFolder
 * Method:    parent
 * Signature: ()Lde/hechler/patrick/pfs/folder/PFSFolder;
 */
JNIEXPORT jobject JNICALL Java_de_hechler_patrick_pfs_folder_impl_NativePatrFileSysFolder_parent__
  (JNIEnv *, jobject);

/*
 * Class:     de_hechler_patrick_pfs_folder_impl_NativePatrFileSysFolder
 * Method:    parent
 * Signature: (Lde/hechler/patrick/pfs/folder/PFSFolder;)V
 */
JNIEXPORT void JNICALL Java_de_hechler_patrick_pfs_folder_impl_NativePatrFileSysFolder_parent__Lde_hechler_patrick_pfs_folder_PFSFolder_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_hechler_patrick_pfs_folder_impl_NativePatrFileSysFolder
 * Method:    move
 * Signature: (Lde/hechler/patrick/pfs/folder/PFSFolder;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_hechler_patrick_pfs_folder_impl_NativePatrFileSysFolder_move
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     de_hechler_patrick_pfs_folder_impl_NativePatrFileSysFolder
 * Method:    iterator
 * Signature: ()Lde/hechler/patrick/interfaces/ThrowableIter;
 */
JNIEXPORT jobject JNICALL Java_de_hechler_patrick_pfs_folder_impl_NativePatrFileSysFolder_iterator
  (JNIEnv *, jobject);

/*
 * Class:     de_hechler_patrick_pfs_folder_impl_NativePatrFileSysFolder
 * Method:    childCount
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hechler_patrick_pfs_folder_impl_NativePatrFileSysFolder_childCount
  (JNIEnv *, jobject);

/*
 * Class:     de_hechler_patrick_pfs_folder_impl_NativePatrFileSysFolder
 * Method:    element
 * Signature: (Ljava/lang/String;)Lde/hechler/patrick/pfs/element/PFSElement;
 */
JNIEXPORT jobject JNICALL Java_de_hechler_patrick_pfs_folder_impl_NativePatrFileSysFolder_element
  (JNIEnv *, jobject, jstring);

/*
 * Class:     de_hechler_patrick_pfs_folder_impl_NativePatrFileSysFolder
 * Method:    folder
 * Signature: (Ljava/lang/String;)Lde/hechler/patrick/pfs/folder/PFSFolder;
 */
JNIEXPORT jobject JNICALL Java_de_hechler_patrick_pfs_folder_impl_NativePatrFileSysFolder_folder
  (JNIEnv *, jobject, jstring);

/*
 * Class:     de_hechler_patrick_pfs_folder_impl_NativePatrFileSysFolder
 * Method:    file
 * Signature: (Ljava/lang/String;)Lde/hechler/patrick/pfs/file/PFSFile;
 */
JNIEXPORT jobject JNICALL Java_de_hechler_patrick_pfs_folder_impl_NativePatrFileSysFolder_file
  (JNIEnv *, jobject, jstring);

/*
 * Class:     de_hechler_patrick_pfs_folder_impl_NativePatrFileSysFolder
 * Method:    pipe
 * Signature: (Ljava/lang/String;)Lde/hechler/patrick/pfs/pipe/PFSPipe;
 */
JNIEXPORT jobject JNICALL Java_de_hechler_patrick_pfs_folder_impl_NativePatrFileSysFolder_pipe
  (JNIEnv *, jobject, jstring);

/*
 * Class:     de_hechler_patrick_pfs_folder_impl_NativePatrFileSysFolder
 * Method:    addFolder
 * Signature: (Ljava/lang/String;)Lde/hechler/patrick/pfs/folder/PFSFolder;
 */
JNIEXPORT jobject JNICALL Java_de_hechler_patrick_pfs_folder_impl_NativePatrFileSysFolder_addFolder
  (JNIEnv *, jobject, jstring);

/*
 * Class:     de_hechler_patrick_pfs_folder_impl_NativePatrFileSysFolder
 * Method:    addFile
 * Signature: (Ljava/lang/String;)Lde/hechler/patrick/pfs/file/PFSFile;
 */
JNIEXPORT jobject JNICALL Java_de_hechler_patrick_pfs_folder_impl_NativePatrFileSysFolder_addFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     de_hechler_patrick_pfs_folder_impl_NativePatrFileSysFolder
 * Method:    addPipe
 * Signature: (Ljava/lang/String;)Lde/hechler/patrick/pfs/pipe/PFSPipe;
 */
JNIEXPORT jobject JNICALL Java_de_hechler_patrick_pfs_folder_impl_NativePatrFileSysFolder_addPipe
  (JNIEnv *, jobject, jstring);

/*
 * Class:     de_hechler_patrick_pfs_folder_impl_NativePatrFileSysFolder
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_hechler_patrick_pfs_folder_impl_NativePatrFileSysFolder_finalize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
