/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_hechler_patrick_pfs_file_impl_NativePatrFileSysFile */

#ifndef _Included_de_hechler_patrick_pfs_file_impl_NativePatrFileSysFile
#define _Included_de_hechler_patrick_pfs_file_impl_NativePatrFileSysFile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_hechler_patrick_pfs_file_impl_NativePatrFileSysFile
 * Method:    getFlags
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hechler_patrick_pfs_file_impl_NativePatrFileSysFile_getFlags
  (JNIEnv *, jobject);

/*
 * Class:     de_hechler_patrick_pfs_file_impl_NativePatrFileSysFile
 * Method:    modifyFlags
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_de_hechler_patrick_pfs_file_impl_NativePatrFileSysFile_modifyFlags
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_hechler_patrick_pfs_file_impl_NativePatrFileSysFile
 * Method:    name
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_hechler_patrick_pfs_file_impl_NativePatrFileSysFile_name__
  (JNIEnv *, jobject);

/*
 * Class:     de_hechler_patrick_pfs_file_impl_NativePatrFileSysFile
 * Method:    name
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_hechler_patrick_pfs_file_impl_NativePatrFileSysFile_name__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     de_hechler_patrick_pfs_file_impl_NativePatrFileSysFile
 * Method:    createTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hechler_patrick_pfs_file_impl_NativePatrFileSysFile_createTime__
  (JNIEnv *, jobject);

/*
 * Class:     de_hechler_patrick_pfs_file_impl_NativePatrFileSysFile
 * Method:    createTime
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_hechler_patrick_pfs_file_impl_NativePatrFileSysFile_createTime__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_hechler_patrick_pfs_file_impl_NativePatrFileSysFile
 * Method:    lastModTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hechler_patrick_pfs_file_impl_NativePatrFileSysFile_lastModTime__
  (JNIEnv *, jobject);

/*
 * Class:     de_hechler_patrick_pfs_file_impl_NativePatrFileSysFile
 * Method:    lastModTime
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_hechler_patrick_pfs_file_impl_NativePatrFileSysFile_lastModTime__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_hechler_patrick_pfs_file_impl_NativePatrFileSysFile
 * Method:    delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_hechler_patrick_pfs_file_impl_NativePatrFileSysFile_delete
  (JNIEnv *, jobject);

/*
 * Class:     de_hechler_patrick_pfs_file_impl_NativePatrFileSysFile
 * Method:    parent
 * Signature: ()Lde/hechler/patrick/pfs/folder/PFSFolder;
 */
JNIEXPORT jobject JNICALL Java_de_hechler_patrick_pfs_file_impl_NativePatrFileSysFile_parent__
  (JNIEnv *, jobject);

/*
 * Class:     de_hechler_patrick_pfs_file_impl_NativePatrFileSysFile
 * Method:    parent
 * Signature: (Lde/hechler/patrick/pfs/folder/PFSFolder;)V
 */
JNIEXPORT void JNICALL Java_de_hechler_patrick_pfs_file_impl_NativePatrFileSysFile_parent__Lde_hechler_patrick_pfs_folder_PFSFolder_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_hechler_patrick_pfs_file_impl_NativePatrFileSysFile
 * Method:    move
 * Signature: (Lde/hechler/patrick/pfs/folder/PFSFolder;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_hechler_patrick_pfs_file_impl_NativePatrFileSysFile_move
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     de_hechler_patrick_pfs_file_impl_NativePatrFileSysFile
 * Method:    read
 * Signature: (J[BI)V
 */
JNIEXPORT void JNICALL Java_de_hechler_patrick_pfs_file_impl_NativePatrFileSysFile_read
  (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     de_hechler_patrick_pfs_file_impl_NativePatrFileSysFile
 * Method:    overwrite
 * Signature: (J[BI)V
 */
JNIEXPORT void JNICALL Java_de_hechler_patrick_pfs_file_impl_NativePatrFileSysFile_overwrite
  (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     de_hechler_patrick_pfs_file_impl_NativePatrFileSysFile
 * Method:    append
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_de_hechler_patrick_pfs_file_impl_NativePatrFileSysFile_append
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     de_hechler_patrick_pfs_file_impl_NativePatrFileSysFile
 * Method:    truncate
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_hechler_patrick_pfs_file_impl_NativePatrFileSysFile_truncate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_hechler_patrick_pfs_file_impl_NativePatrFileSysFile
 * Method:    length
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hechler_patrick_pfs_file_impl_NativePatrFileSysFile_length
  (JNIEnv *, jobject);

/*
 * Class:     de_hechler_patrick_pfs_file_impl_NativePatrFileSysFile
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_hechler_patrick_pfs_file_impl_NativePatrFileSysFile_finalize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
