/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_hechler_patrick_pfs_pipe_impl_NativePatrFileSysPipe */

#ifndef _Included_de_hechler_patrick_pfs_pipe_impl_NativePatrFileSysPipe
#define _Included_de_hechler_patrick_pfs_pipe_impl_NativePatrFileSysPipe
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_hechler_patrick_pfs_pipe_impl_NativePatrFileSysPipe
 * Method:    getFlags
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hechler_patrick_pfs_pipe_impl_NativePatrFileSysPipe_getFlags
  (JNIEnv *, jobject);

/*
 * Class:     de_hechler_patrick_pfs_pipe_impl_NativePatrFileSysPipe
 * Method:    modifyFlags
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_de_hechler_patrick_pfs_pipe_impl_NativePatrFileSysPipe_modifyFlags
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_hechler_patrick_pfs_pipe_impl_NativePatrFileSysPipe
 * Method:    name
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_hechler_patrick_pfs_pipe_impl_NativePatrFileSysPipe_name__
  (JNIEnv *, jobject);

/*
 * Class:     de_hechler_patrick_pfs_pipe_impl_NativePatrFileSysPipe
 * Method:    name
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_hechler_patrick_pfs_pipe_impl_NativePatrFileSysPipe_name__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     de_hechler_patrick_pfs_pipe_impl_NativePatrFileSysPipe
 * Method:    createTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hechler_patrick_pfs_pipe_impl_NativePatrFileSysPipe_createTime__
  (JNIEnv *, jobject);

/*
 * Class:     de_hechler_patrick_pfs_pipe_impl_NativePatrFileSysPipe
 * Method:    createTime
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_hechler_patrick_pfs_pipe_impl_NativePatrFileSysPipe_createTime__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_hechler_patrick_pfs_pipe_impl_NativePatrFileSysPipe
 * Method:    lastModTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hechler_patrick_pfs_pipe_impl_NativePatrFileSysPipe_lastModTime__
  (JNIEnv *, jobject);

/*
 * Class:     de_hechler_patrick_pfs_pipe_impl_NativePatrFileSysPipe
 * Method:    lastModTime
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_hechler_patrick_pfs_pipe_impl_NativePatrFileSysPipe_lastModTime__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_hechler_patrick_pfs_pipe_impl_NativePatrFileSysPipe
 * Method:    delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_hechler_patrick_pfs_pipe_impl_NativePatrFileSysPipe_delete
  (JNIEnv *, jobject);

/*
 * Class:     de_hechler_patrick_pfs_pipe_impl_NativePatrFileSysPipe
 * Method:    parent
 * Signature: ()Lde/hechler/patrick/pfs/folder/PFSFolder;
 */
JNIEXPORT jobject JNICALL Java_de_hechler_patrick_pfs_pipe_impl_NativePatrFileSysPipe_parent__
  (JNIEnv *, jobject);

/*
 * Class:     de_hechler_patrick_pfs_pipe_impl_NativePatrFileSysPipe
 * Method:    parent
 * Signature: (Lde/hechler/patrick/pfs/folder/PFSFolder;)V
 */
JNIEXPORT void JNICALL Java_de_hechler_patrick_pfs_pipe_impl_NativePatrFileSysPipe_parent__Lde_hechler_patrick_pfs_folder_PFSFolder_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_hechler_patrick_pfs_pipe_impl_NativePatrFileSysPipe
 * Method:    move
 * Signature: (Lde/hechler/patrick/pfs/folder/PFSFolder;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_hechler_patrick_pfs_pipe_impl_NativePatrFileSysPipe_move
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     de_hechler_patrick_pfs_pipe_impl_NativePatrFileSysPipe
 * Method:    read
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_de_hechler_patrick_pfs_pipe_impl_NativePatrFileSysPipe_read
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     de_hechler_patrick_pfs_pipe_impl_NativePatrFileSysPipe
 * Method:    append
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_de_hechler_patrick_pfs_pipe_impl_NativePatrFileSysPipe_append
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     de_hechler_patrick_pfs_pipe_impl_NativePatrFileSysPipe
 * Method:    length
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_hechler_patrick_pfs_pipe_impl_NativePatrFileSysPipe_length
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
